# Generated by Django 4.0.1 on 2022-01-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='채팅방 비밀번호'),
        ),
    ]
