# Generated by Django 4.0.1 on 2022-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
