# Generated by Django 4.0.1 on 2022-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_directroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_system',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
