# Generated by Django 4.0.1 on 2022-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_is_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_system',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='m_type',
            field=models.CharField(choices=[('ENTER', 'Enter'), ('EXIT', 'Exit'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10, verbose_name='메세지타입'),
        ),
    ]
