# Generated by Django 4.0.1 on 2022-02-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatmessage_is_system_chatmessage_m_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='basic', max_length=100, verbose_name='채팅방타입'),
        ),
    ]
